import { sleep } from '../../utils/time.js';

let pluginConfig = { intervalSeconds: 5 };

export default {
  name: 'mock',
  description: 'Emits fake OWL events for testing the daemon, world model, and discovery engine.',

  async setup(config = {}) {
    pluginConfig = { ...pluginConfig, ...config };
  },

  async *watch() {
    let counter = 0;
    while (true) {
      counter += 1;
      yield {
        source: 'mock',
        type: counter % 2 === 0 ? 'email.received' : 'calendar.event.created',
        timestamp: new Date().toISOString(),
        summary:
          counter % 2 === 0
            ? `Email from John Smith at Acme about Q${counter} pricing`
            : `Meeting with John Smith and Acme scheduled for tomorrow`,
        data: {
          subject: `Mock signal ${counter}`,
          snippet: 'This is a fake but structured event generated by OWL mock plugin.',
          attendees: ['John Smith <john@acme.com>'],
          from: 'John Smith <john@acme.com>',
          to: 'Markuss <markuss@example.com>'
        },
        importance: counter % 3 === 0 ? 0.75 : 0.55
      };

      await sleep((pluginConfig.intervalSeconds || 5) * 1000);
    }
  },

  async query() {
    return { status: 'ok', plugin: 'mock' };
  }
};
