import path from 'node:path';
import { formatDiscoveryMessage } from './manager.js';
import { appendNdjson, readNdjson, writeNdjson } from '../utils/fs.js';

export function getEmailDigestQueuePath(deliveryQueuePath) {
  return path.join(path.dirname(deliveryQueuePath || '.'), 'email-digest-queue.ndjson');
}

const URGENCY_COLORS = {
  urgent: '#ff3b30',
  important: '#ffcc00',
  interesting: '#34c759'
};

const TYPE_LABELS = {
  connection: '\u{1F517} Connection',
  anomaly: '\u{26A0}\u{FE0F} Anomaly',
  risk: '\u{1F6A8} Risk',
  opportunity: '\u{1F4A1} Opportunity',
  anticipation: '\u{1F52E} Anticipation',
  time_sensitive: '\u{23F0} Time-Sensitive'
};

/**
 * Group discoveries by theme: shared entities, sources, or type.
 * Returns an array of { label, discoveries } clusters.
 */
function groupDiscoveries(discoveries) {
  if (discoveries.length <= 2) {
    return [{ label: null, discoveries }];
  }

  // Try to cluster by shared entities
  const clusters = [];
  const used = new Set();

  // Pass 1: group by overlapping entities
  for (let i = 0; i < discoveries.length; i++) {
    if (used.has(i)) continue;
    const cluster = [discoveries[i]];
    used.add(i);
    const entitySet = new Set(discoveries[i].entities || []);

    for (let j = i + 1; j < discoveries.length; j++) {
      if (used.has(j)) continue;
      const overlap = (discoveries[j].entities || []).some((e) => entitySet.has(e));
      if (overlap) {
        cluster.push(discoveries[j]);
        used.add(j);
        for (const e of discoveries[j].entities || []) entitySet.add(e);
      }
    }

    if (cluster.length > 1) {
      const sharedEntities = [...entitySet].slice(0, 3).join(', ');
      clusters.push({ label: `Related to ${sharedEntities}`, discoveries: cluster });
    }
  }

  // Pass 2: group remaining by type
  const remaining = discoveries.filter((_, i) => !used.has(i));
  const byType = {};
  for (const d of remaining) {
    const type = d.type || 'other';
    if (!byType[type]) byType[type] = [];
    byType[type].push(d);
  }

  for (const [type, items] of Object.entries(byType)) {
    if (items.length > 1) {
      clusters.push({ label: TYPE_LABELS[type] || type, discoveries: items });
    } else {
      clusters.push({ label: null, discoveries: items });
    }
  }

  return clusters.length > 0 ? clusters : [{ label: null, discoveries }];
}

function formatHtml(discoveries) {
  const clusters = groupDiscoveries(discoveries);

  const sections = clusters.map((cluster) => {
    const header = cluster.label
      ? `<h2 style="color:#333;border-bottom:1px solid #ddd;padding-bottom:8px;">${cluster.label}</h2>`
      : '';

    const items = cluster.discoveries.map((discovery) => {
      const color = URGENCY_COLORS[discovery.urgency] || URGENCY_COLORS.interesting;
      const typeLabel = TYPE_LABELS[discovery.type] || discovery.type;

      return `<div style="margin:16px 0;padding:16px;border-left:4px solid ${color};background:#fafafa;border-radius:4px;">
  <h3 style="margin:0 0 8px 0;color:#222;">${discovery.title}</h3>
  <p style="margin:0 0 8px 0;color:#555;">${discovery.body}</p>
  <p style="margin:0;font-size:0.85em;color:#888;">
    ${typeLabel} &middot; ${discovery.urgency} &middot; Sources: ${(discovery.sources || []).join(', ')}
    ${discovery.confidence != null ? ` &middot; ${Math.round(discovery.confidence * 100)}% confidence` : ''}
  </p>
</div>`;
    }).join('');

    return header + items;
  }).join('');

  return `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;">
  <h1 style="color:#333;">\u{1F989} OWL Daily Digest</h1>
  ${sections}
  <p style="margin-top:24px;font-size:0.8em;color:#aaa;">Generated by OWL &middot; Reply to any discovery to give feedback</p>
</div>`;
}

function formatText(discoveries) {
  return discoveries.map(formatDiscoveryMessage).join('\n\n---\n\n');
}

export class EmailDigestChannel {
  constructor(config = {}, deps = {}) {
    this.name = 'email-digest';
    this.config = config;
    this.logger = deps.logger;
    this.queuePath =
      deps.digestQueuePath ||
      getEmailDigestQueuePath(deps.deliveryQueuePath);
  }

  async send(discoveries) {
    for (const discovery of discoveries) {
      appendNdjson(this.queuePath, discovery);
    }

    this.logger?.info('Queued discoveries for email digest delivery', { count: discoveries.length });
  }

  async flush() {
    const pending = readNdjson(this.queuePath);
    if (pending.length === 0) {
      return;
    }

    if (!this.config.apiKey || !this.config.to || !this.config.from) {
      this.logger?.warn('Email digest is queued but provider settings are incomplete');
      return;
    }

    if (this.config.provider !== 'resend') {
      this.logger?.warn('Email digest currently supports the Resend API only');
      return;
    }

    const deduped = Array.from(
      new Map(pending.map((item) => [item.id || `${item.title}:${item.timestamp}`, item])).values()
    ).sort((left, right) => {
      // Sort by urgency first, then by timestamp
      const urgencyOrder = { urgent: 0, important: 1, interesting: 2 };
      const urgencyDiff = (urgencyOrder[left.urgency] || 2) - (urgencyOrder[right.urgency] || 2);
      if (urgencyDiff !== 0) return urgencyDiff;
      return String(left.timestamp || '').localeCompare(String(right.timestamp || ''));
    });

    const urgentCount = deduped.filter((d) => d.urgency === 'urgent').length;
    const subject = urgentCount > 0
      ? `\u{1F534} OWL: ${urgentCount} urgent + ${deduped.length - urgentCount} more discoveries`
      : `\u{1F989} OWL discoveries (${deduped.length})`;

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        authorization: `Bearer ${this.config.apiKey}`,
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        from: this.config.from,
        to: [this.config.to],
        subject,
        text: formatText(deduped),
        html: formatHtml(deduped)
      })
    });

    if (!response.ok) {
      throw new Error(`Resend API failed with ${response.status}`);
    }

    writeNdjson(this.queuePath, []);
    this.logger?.info('Delivered email digest', { count: deduped.length });
  }
}

// Export for testing
export { groupDiscoveries, formatHtml };
